--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Feb 05 2018 09:25
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'TurneringsSkakklub'   
-- TSKId           :  
--
CREATE TABLE TurneringsSkakklub (
    TSKId          BIGINT IDENTITY(1,1) NOT NULL,
CONSTRAINT pk_TurneringsSkakklub PRIMARY KEY CLUSTERED (TSKId))