SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
--SET TRANSACTION ISOLATION LEVEL SNAPSHOT
BEGIN TRAN  
SELECT * FROM IsolationTests  
WAITFOR DELAY '00:00:10'  
SELECT * FROM IsolationTests  
ROLLBACK  