--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 11 2018 09:57
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'Entity5'   
-- IF5             :  
--
CREATE TABLE Entity5 (
    IF5            BIGINT IDENTITY(1,1) NOT NULL,
CONSTRAINT pk_Entity5 PRIMARY KEY CLUSTERED (IF5))